### PR TITLE
Change doc structure

### PR DESCRIPTION
**Pull request by derekjuber**
Based on the future re-org of our internal docs, mirror the same structure for the open source docs so that we can set this up for adding more content in the future.

Changes are:

1) Guides are renamed to References and all wording and links were changed to reflect this
2) Moved Core concepts and Framework comparison to a new Learn Fusion part
3) Widens the page layout to be consistent

### CODE REVIEW

**Comment by lhorie** [comment]
Maybe it's just me, but I'd find it more helpful to have the guides/references be more prominent than the "core concepts" and "framework comparison" pages. I actually think what were called guides before fit better under the category of "Learn Fusion", since they actually go over how to do various things, whereas I think of those two pages more as reference pages (i.e. pages I'd come back to consult if I was curious)

**Comment by angus-c** [comment]
I think "core concepts" is a good way to start the document—a sort of "why fusion?". Maybe it could be a little briefer, so that it doesn't delay the reader too much before they dive into the juicier bits.

**Comment by lhorie** [comment]
Core concepts is more like a glossary

**Comment by derekjuber** [comment]
Agreed in general. This is more matching the layout for our internal docs for now so that the two are following a similar layout. I plan on fleshing out the documentation more for this site so that the relevant categories have more information at a future date.

It's kind of a limitation of the way we are pulling external docs into our internal site in that the layouts have to be the same in order for the compiler to recognize which doc needs to be pulled. Either that whole system is refactored (which I really don't want to do) or we go with a shared layout for now even if it makes some of the external docs sparse for now. Given that this is an ongoing effort and will not fall by the wayside, I'm ok with moving forward with this nav layout for now.

**Pull request merged**
